'------------------------------------------------------------------------------
' <auto-generated>
'     Ten kod został wygenerowany przez narzędzie.
'     Wersja wykonawcza:4.0.30319.42000
'
'     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
'     kod zostanie ponownie wygenerowany.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    'przez narzędzie, takie jak ResGen lub Visual Studio.
    'Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    'z opcją /str lub ponownie utwórz projekt VS.
    '''<summary>
    '''  Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Radan_Magazyn_Blach_Moduł_Zarządzający.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        '''  przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _111() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("111", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property calendar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calendar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property disc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property p2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property radan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("radan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sl_rma2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sl-rma2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
